### ISSUE TITLE
Makefile has some typos

### ISSUE THREAD

**Issue by cbuijs** [FvDxxx/pfxaggr#3]
The [compile line](https://github.com/FvDxxx/pfxaggr/blob/09653969f954100dd3246f85a2ae75194599c41f/Makefile#L23) uses `pfxagg` (without an "r" at the end), and the rest (line [#17](https://github.com/FvDxxx/pfxaggr/blob/09653969f954100dd3246f85a2ae75194599c41f/Makefile#L17), [#26](https://github.com/FvDxxx/pfxaggr/blob/09653969f954100dd3246f85a2ae75194599c41f/Makefile#L26) and [#29-#31](https://github.com/FvDxxx/pfxaggr/blob/09653969f954100dd3246f85a2ae75194599c41f/Makefile#L29-L33)) uses `pfxaggr` (with a "r" at the end).

**Comment by FvDxxx** [comment]
Thanks. Changed for consistency and to be inline with the README.
